### PR TITLE
Ported pysmt from pycudd to repycudd

### PR DESCRIPTION
**Pull request by mikand**
Ported pysmt BDD solving features to use repycudd version of pycudd, thus having a re-entrant version of the library

### CODE REVIEW

**Comment by marcogario** [comment]
Good!
Update README and CHANGES, to make it clear that we are wrapping repycudd and not pycudd.

**Comment by mikand** [comment]
If you can, put online a mirror for CI, so that we can avoid the hack I added in install.py

**Comment by marcogario** [comment]
@mikand, done. Please squash this PR.

**Comment by mikand** [comment]
Done

**Pull request merged**
