### PR TITLE
Fixed CVC4 Installer to use binding dir for CVC4_bin

### PR DESCRIPTION
**Pull request by marcogario**
This solves the caching problem in Travis

### CODE REVIEW

**Comment by mikand** [comment]
Great! :+1: 

But it seems that Z3 and Yices are not cached as well, shall we handle this here or in another PR?

**Comment by mikand** [comment]
ANother note: maybe we can add the compilation flag you reported in #205

**Comment by marcogario** [comment]
The main goal was to reduce the time it takes to perform CI. Now it takes at most 5 minutes. I'd suggest that we look at the other cases in a different PR.
Also, note that caches are divided by python version, so I am wondering if the hack done for boolector is really needed.

Also for the flag, I am opening a new branch, with an updated version of CVC4.

**Comment by marcogario** [comment]
I am closing this, so that the next PRs can benefit from faster building times.

**Pull request merged**
