### PR TITLE
 Link to Google Group in Readme.md

### PR DESCRIPTION
**Pull request by ankit01ojha**
Added the button and link

### CODE REVIEW

**Comment by marcogario** [comment]
Hi, thanks for working on this. In order for me to accept the PR I need you to:

* Sign the CLA (clahub link you see in this PR)
* Squash these commits into a unique commit (See for example http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

Thanks

**Comment by nitishkd** [comment]
Though, I made the PR first I guess. Nevermind.

**Comment by nitishkd** [comment]
Oh Sorry, I meant to post this on my thread.

**Comment by marcogario** [comment]
@ankit01ojha , do you think you can sign the CLA and squash these commits? That's all is missing for me to accept this PR. Thank you.

**Comment by marcogario** [comment]
@ankit01ojha, are you planning on completing this?

**Comment by ankit01ojha** [comment]
Sorry, but I have signed the CLA but its still not taking.

**Comment by marcogario** [comment]
The email address that you are using in the git commits does not match the one you use in clahub. In fact, notice that next to your commit message, the avatar is a generic one, and not your profile image. 
You can change that following the instructions in [1]. 

I'll go ahead and accept this. Thank you for contributing!

[1] https://help.github.com/articles/setting-your-email-in-git/

**Pull request merged**
