### PR TITLE
Upgrade Yices to 2.54 and add macOS support

### PR DESCRIPTION
**Pull request by varunpatro**

### CODE REVIEW

**Comment by varunpatro** [comment]
This PR partially solves #96 and fully solves #461 and #412.

**Comment by marcogario** [comment]
Thanks for the patch!
Can you confirm that the tests are passing on osx?

I get the following failure [1] from our CI both for python and python 2.

```
pysmt.test.smtlib.test_parser_qf_lia.test_generator('pysmt/test/smtlib/small_set/QF_LIA/prp-23-47.smt2.bz2', QF_LIA, False) ... /Users/travis/.travis/job_stages: line 57:  5359 Illegal instruction: 4  ${PYTHON_EXE} -mnose pysmt -v
```

[1] https://travis-ci.org/pysmt/pysmt/jobs/384114232

**Comment by marcogario** [comment]
https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

**Comment by varunpatro** [comment]
That's really strange. Because I'm running 10.13.4 and it builds and runs fine on my computer. Let me test this a little more.

In the worst case, if the yices2 binary only works on some os versions, is there a way to halt the installation and alert this to the user?

**Comment by marcogario** [comment]
The issue might be also be in the python wrapper. In particular, if the version of xcode is different than the version used for building yices. If this is the case, it should be possible to add a backwards compatibility flag when building yicespy.

If there is an issue with Yices, we should report it upstream and see how to proceed. We typically do build from source if there are these types of issues. The problem is that in those cases it takes quite a bit to install some solvers.

**Comment by mikand** [comment]
@marcogario I think that this PR improves the status of the Yices solver anyway. Maybe we can merge this and then deal with the problem of making yices work under OSX on our CI separately (e.g. in #491). What do you think?

**Comment by marcogario** [comment]
Ok to only include linux upgrade. Please keep a pr open for the macos support. We can maybe ask other macos users for ideas on how to debug this.

**Comment by mikand** [comment]
OK, I'll merge this then I will try to see if I manage to make yices to work in #491

**Comment by mikand** [comment]
BTW, I just found this: http://yices.csl.sri.com/faq.html  :shamrock: 
It seems that the Travis VM does not have the needed CPU flag enabled...

**Pull request merged**
