### PR TITLE
 CLA: Add utility to check for CLA

### PR DESCRIPTION
**Pull request by marcogario**
We require all contributors to submit a change to CONTRIBUTORS as a way to confirming acceptance of the CLA.

To check this, we compare the git log with the entries in the CONTRIBUTORS file.

Since users might have sent commits with different names/emails, we introduce a `.mailmap` to provide canonical names.

The CONTRIBUTORS data has been updated with the content of CLAHub.

We seem to be missing a few:
image

Require CLA:
* Caleb Donovick b0f031d9f595dddbd4febd3dd3bad487f3e112d9
* en.magnago 2b9a879ac9fbe9253d05655b3212dd0a13a37273

Typos in documentation (might consider whitelisting these changes)
* Guillem Francès 6562e2662496291a5578facecb140d7f41f8ab4d
* Matthew Fernandez 39e6d252239d63472b2a28a901bd0bcce42237dd

### CODE REVIEW

**Comment by marcogario** [comment]
@mikand What do you think of this approach? I think it is much more lightweight and as good as CLAHub.
It seems we need to trace back a few commits to see what changes the missing people did.

**Comment by mikand** [comment]
I like it very much. Shall we use this PR to ask the four missing people to add themselves to the CONTRIBUTORS (they can open a PR to this branch) or do you see another way?

**Comment by marcogario** [comment]
The only drawback of this approach is that we need to be careful with rewriting history. I think the easiest is to always open a PR against master to modify the CONTRIBUTORs file. The lightweight approach is to avoid history rewriting on PRs, but I think that is not good in the long run.

I wanted to track down the contributions of these individuals prior to reaching out.

**Comment by marcogario** [comment]
:wave: @cdonovick 

Thanks for contributing to pySMT (https://github.com/pysmt/pysmt/commit/b0f031d9f595dddbd4febd3dd3bad487f3e112d9). We are updating our CLA process and realized we are missing the CLA acceptance from you.

Could you do the following?
* Review our CLA: https://github.com/pysmt/pysmt/blob/cla/docs/development.rst#licensing . 
   * **NOTE** The CLA has NOT changed (Apache + “Developer Certificate of Origin”). Only our process has changed as we relied on an external tool that is not supported anymore.
* [Click here](https://github.com/pysmt/pysmt/edit/cla/CONTRIBUTORS), and add `Caleb Donovick <donovick@cs.stanford.edu>` (name and email address used in git) to the CONTRIBUTORS file in this branch  (Please keep the alphabetic order)
* Open a PR against this branch with the changes

You should be able to do this from your browser by using the link above, so I hope it will be quick. 
Apologies for not catching this earlier. :bowing_man:

**Comment by marcogario** [comment]
:wave: @EnricoMagnago  

Thanks for contributing to pySMT (https://github.com/pysmt/pysmt/commit/2b9a879ac9fbe9253d05655b3212dd0a13a37273). We are updating our CLA process and realized we are missing the CLA acceptance from you.

Could you do the following?
* Review our CLA: https://github.com/pysmt/pysmt/blob/cla/docs/development.rst#licensing . 
   * **NOTE** The CLA has NOT changed (Apache + “Developer Certificate of Origin”). Only our process has changed as we relied on an external tool that is not supported anymore.
* [Click here](https://github.com/pysmt/pysmt/edit/cla/CONTRIBUTORS), and add `Enrico Magnago <en.magnago@gmail.com>` (by eventually correcting your full name) to the CONTRIBUTORS file in this branch. (Please keep the alphabetic order)
* Open a PR against this branch with the changes

You should be able to do this from your browser by using the link above, so I hope it will be quick. 
Apologies for not catching this earlier. :bowing_man:

**Comment by cdonovick** [comment]
Sorry I missed this. PR is up.

**Comment by mikand** [comment]
@marcogario I would go ahead and merge this before any other PR so that we forcibly collect all the "signatures"

**Pull request merged**
