### PR TITLE
Fix bug in deque pop in smtlib/parser

### PR DESCRIPTION
**Pull request by Phat3**
Collection.deque does not have a method pop that takes arguments (i.e. `pop(0)` does not exist). I replaced the method with `popleft()` which achieve the same result as the intended one.

### CODE REVIEW

**Comment by mikand** [comment]
@Phat3 Thanks for this! It probably slipped into when we changed from a list to a deque for performance.

Do you have an SMT2 example we can add to the test-suite that triggers the problem with the old code? It would be great to add it as a no-regression test.

**Comment by Phat3** [comment]
Yep sure! 

The SMT-LIB script that cause the problem for me is  the following:

```
(model
(define-fun STRING_cmd_line_arg_1_1000 () String "AAAAAAAAAAAA")
)
```

Should I provide a real test case or this is fine?

**Comment by mikand** [comment]
If you could put this in a testcase in e.g. `pysmt/test/smtlib/test_parser_examples.py` it would be great!

**Comment by Phat3** [comment]
Test case added :+1:

**Comment by mikand** [comment]
@Phat3 Thanks a lot for this PR!

**Pull request merged**
