### PR TITLE
adding Arrighi, Contaldo and Trentin as contributors

### PR DESCRIPTION
**Pull request by cespio**
Adding Arrighi, Contaldo and Trentin as contributors

### CODE REVIEW

**Comment by PatrickTrentin88** [comment]
I approve the change being made in my name. Thank you for doing so.

**Comment by mikand** [comment]
Thanks for the confirmation @PatrickTrentin88 !

Waiting for confirmation from Francesco Arrighi

**Comment by arrighi79** [comment]
I approve the change being made in my name. Thank you and good day.

**Comment by mikand** [comment]
Perfect, thanks a lot!

**Pull request merged**
