### PR TITLE
Fix pysmt CLI for Python3 (closes #492)

### LINKED ISSUE #492: pysmt command fails in Python3
After clean `pip install pysmt` in a Python 3 virtual env:
```
$ pysmt
Traceback (most recent call last):
  File "/tmp/tmp.QmRID1iOu8/bin/pysmt", line 11, in <module>
    sys.exit(main())
  File "/tmp/tmp.QmRID1iOu8/lib/python3.5/site-packages/pysmt/cmd/shell.py", line 144, in main
    shell = PysmtShell(sys.argv[1:])
  File "/tmp/tmp.QmRID1iOu8/lib/python3.5/site-packages/pysmt/cmd/shell.py", line 63, in __init__
    self.parser = self.get_parser()
  File "/tmp/tmp.QmRID1iOu8/lib/python3.5/site-packages/pysmt/cmd/shell.py", line 80, in get_parser
    choices=['auto'] + self.solvers,
TypeError: can only concatenate list (not "dict_keys") to list
```

### PR DESCRIPTION
**Pull request by randomir**
To append `dict_keys` to `list`, need to explicitly convert them.

### CODE REVIEW

**Comment by marcogario** [comment]
Thanks for submitting the patch. I am just restarting the CI due to a known issue with Z3, but I will merge it asap.

**Comment by randomir** [comment]
No worries.

Btw, while we're on topic of Z3 -- would you be interested in a PR which would change Z3 installer, so the `LD_LIBRARY_PATH` hack is no longer needed?

**Comment by randomir** [comment]
On that note, can you please take a look at #494 -- an attempt to get rid of `LD_LIBRARY_PATH`/`PATH`. Z3 discovers its library in `./lib` and mathsat can be linked to look for libs relative to the binary.

**Comment by randomir** [comment]
Hey @marcogario, I believe this PR is now good to merge. Btw, any thoughts on #494 (see comment above)?

**Comment by mikand** [comment]
@randomir Thanks a lot for the patch!

**Pull request merged**
