### PR TITLE
example/parallel.py: typo fix

### PR DESCRIPTION
**Pull request by tias**
minimal doc change

### CODE REVIEW

**Comment by mikand** [comment]
Thanks @tias !

Can you add your name and emails in the CONTRIBUTORS file to mark the acceptance of the pysmt CLA?

**Comment by tias** [comment]
OK done.

Note that the CLAhub link on 
https://pysmt.readthedocs.io/en/latest/development.html

does not work, and also that I think you moved from nosetest to pytest (lower on that page).

Kind regards,
Tias

**Comment by mikand** [comment]
@tias Thanks for the report! 

It seems that the readthedocs is out-of-sync, I'll look into this ASAP. See https://github.com/pysmt/pysmt/blob/master/docs/development.rst for the updated doc.

Instead, from the CI it seems that you used a different email for your commits (Tias Guns <tias@ulyssis.org>), we are checking that all the contributors emails are in the `CONTRIBUTORS` file. Can you please add the correct email (or an alias in the `.mailmap` file).

**Comment by mikand** [comment]
Thanks @tias .
I know this procedure is a burden, but alt least is a one-shot thing. From now on you can contribute without problems :)

**Pull request merged**
