### PR TITLE
OMT parsing

### PR DESCRIPTION
**Pull request by cespio**
Hi all, this is my first pull request for this project. I have talked in advance with @mikand  about the idea to include my master thesis work  (https://github.com/cespio/omt2mzn) in this project

This first pull request wants to extend the parsing capabilities of pysmt in order to understand the following SMTLIB-v2 extension http://optimathsat.disi.unitn.it/pages/smt2reference.html

The other pull requests will be more focused on the actual omt2mzn translation

### CODE REVIEW

**Comment by mikand** [comment]
@cespio Thanks for this. I'll change the destination branch from master to optimization, and then code-review this.

**Comment by mikand** [comment]
@cespio Would it be possible to rebase these changes on top of the `optimization` branch? This would simplify my code-review a bit :smile:

**Comment by cespio** [comment]
@mikand I should have done, but I am not sure if what I have done is correct :smile:

**Comment by mikand** [comment]
@cespio The PR looks good to me, but it includes way more commits than necessary.
I I merge it like it is, it will cause a bit of a mess in the optimization branch.

Can you please do the following?

1. `git rebase optimization` on your branch
2. fix any conflict, if needed
3. `git push -f`

(https://medium.com/@dirk.avery/the-definitive-git-rebase-guide-dbd7717f9437)

If you encounter any issue let me know.

**Comment by cespio** [comment]
@mikand I did what you told me, let me know if it is correct!

**Comment by mikand** [comment]
Nope. There are still very strange commits in the history. Maybe the easiest thing is if you give me access to cespio/pysmt and I'll rewrite the of the branch directly. Otherwise I'll open a new branch and cherry-pick your commits...

**Comment by cespio** [comment]
@mikand I have just gave you the acess, thanks :slightly_smiling_face: :pray:

**Comment by mikand** [comment]
Closing in favor of #642

**Pull request closed without merging**
